name: Build and Push Image
on:
  push:
    paths:
      - "images/**"
  workflow_dispatch:
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: [build]
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Set image name
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "image=ghcr.io/${REPO_LOWER}/<image-name>" >> "$GITHUB_OUTPUT"


      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ steps.vars.outputs.image }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} images

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ steps.vars.outputs.image }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
